# Generated by Django 5.0.6 on 2024-06-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images/'),
        ),
    ]
