# Generated by Django 5.0.6 on 2024-06-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkDescription',
            field=models.CharField(default=None, max_length=4000),
        ),
    ]
