# Generated by Django 5.0.6 on 2024-06-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image2_post_image3_post_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=4000),
        ),
        migrations.AlterField(
            model_name='post',
            name='linkDescription',
            field=models.CharField(blank=True, default=None, max_length=4000),
        ),
    ]
