# Generated by Django 5.0.6 on 2024-06-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fps1080', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fps1440', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fps4k', models.DecimalField(decimal_places=2, max_digits=9)),
                ('AvgPower', models.IntegerField()),
                ('itemDescription', models.CharField(max_length=4000000)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Component.component')),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('avgTemp', models.DecimalField(decimal_places=2, max_digits=9)),
                ('socket', models.CharField(max_length=80)),
            ],
            bases=('Component.component',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Component.component')),
                ('avgTemp', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            bases=('Component.component',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Component.component')),
                ('formFactor', models.CharField(max_length=20)),
            ],
            bases=('Component.component',),
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Component.component')),
                ('watts', models.IntegerField()),
                ('modular', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=280)),
                ('psRank', models.CharField(max_length=200)),
            ],
            bases=('Component.component',),
        ),
    ]
