# Generated by Django 5.0.6 on 2024-06-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Component', '0003_component_yearreleased_gpu_fpsrt1080_gpu_fpsrt1440_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='avgTemp',
        ),
    ]
