# Generated by Django 5.0.6 on 2024-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Component', '0004_remove_gpu_avgtemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='avgTemp',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='threads',
        ),
        migrations.AddField(
            model_name='cpu',
            name='appscore',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cpu',
            name='score1080',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cpu',
            name='score1440',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
